nombre_apellido = input("Ingrese su nombre y apellido: ")
nota1 = int(input("Ingrese la primer nota: "))
nota2 = int(input("Ingrese la segunda nota: "))
nota3 = int(input("Ingrese la tercer nota: "))
print("El promedio es:", (nota1 + nota2 + nota3) / 3 )